sudo: false
language: ruby
rvm:
  - "2.2.3"
script: bundle exec rake db:create db:migrate spec cucumber RAILS_ENV=test
addons:
  postgresql: "9.3"
before_script:
  - psql -c 'create database foosball_test;' -U postgres
  - cp config/database.yml.travis config/database.yml
